---
common:
  log_level: 1
gcc:
  version: gcc 9.3.0
  options_whitelist:
    - "-v"
    - "-g"
    - "--version"
    - "--verbose"
    - "-Wall"

rustc:
  version: rustc 1.58.0-nightly
  options_whitelist:
    - "-v"
    - "-g"
    - "--version"
    - "--verbose"
    - "-Wall"
