sessions_data_dir: sessions_data/
sessions_data_file: sessions_data/sessions_data.txt
# Unit of measurement for time here is a millisecond
session_life_duration: 500000
sessions_cleanup_interval: 1000000
sessions_save_interval: 1000000

lang_extensions:
  c++: .cpp
  # rust: .rs # Not implemented yet
